### ISSUE TITLE
`MonadFix` instance is needlessly strict

### ISSUE THREAD

**Issue by gergoerdi** [DanBurton/rev-state#2]
As explained on http://stackoverflow.com/a/34287498/477476 , `RevState`'s `MonadFix` instance is too strict and is practically unusable as a result. The fix is a trivial matter of using an irrefutable pattern in the instance definition; i.e. going from

```
instance MonadFix m => MonadFix (StateT s m) where
  mfix f = StateT $ \s -> mfix (\(x, _) -> runStateT (f x) s)
```

to

```
instance MonadFix m => MonadFix (StateT s m) where
  mfix f = StateT $ \s -> mfix (\ ~(x, _) -> runStateT (f x) s)
```

**Comment by DanBurton** [comment]
Thanks for the bugfix! I've whipped up a little test suite based on the example in that SO question.
