### ISSUE TITLE
MonadTrans instance?

### ISSUE THREAD

**Issue by wavewave** [DanBurton/rev-state#3]
I wonder if MonadTrans instance for reverse state monad is deliberately not provided, or simply not done yet? If there is an obstacle to define MonadTrans instance, could you explain it to me?

**Comment by DanBurton** [comment]
I probably just forgot. Feel free to send a PR, or I'll get around to this sometime.

**Comment by DanBurton** [comment]
Uploaded rev-state-0.1.2. This might break with older versions of base; let me know if it's a problem.
